### ISSUE TITLE
Do you have an example capture file?

### ISSUE THREAD

**Issue by hadrielk** [diarmuidcwc/LuaDissectors#1]
Hi,
I'd like to add your Lua plugin scripts to Wireshark's repository (I'm one of the developers).
Do you have an example packet capture(s) to use with the scripts, that you would be willing to have publicly viewable?
-hadriel

**Comment by diarmuidcwc** [comment]
Hi Hadriel

I have written some python classes that pack and unpacket iNetX and IENA formats. In the unittest for those classes I have some sample pcap files. You can find them here
https://github.com/diarmuidcwc/AcraNetwork/tree/master/test

Is that sufficient?
Diarmuid

**Comment by hadrielk** [comment]
Yup that's great - thanks!

**Comment by diarmuidcwc** [comment]
Done
